//
// Created by Peter Szathmáry on 11/05/2022.
//

#ifndef SZATHMARY_SEMESTRALNA_PRACA_UZEMNAJEDNOTKATYP_H
#define SZATHMARY_SEMESTRALNA_PRACA_UZEMNAJEDNOTKATYP_H


enum UzemnaJednotkaTyp
{
    OBEC,
    KRAJ,
    OKRES,
    STAT
};


#endif //SZATHMARY_SEMESTRALNA_PRACA_UZEMNAJEDNOTKATYP_H
